GUI:
  Title: "!#8602e1&lAmazing!#c148f3!#c148f3&lTags!#f74c34"
  
  Items:
    Preview:
      Name: "&5&lSelected tag:"
      Lore:
      - "&7Selected: %tagname%"
      - "&7Tag: %tag%"
      - "&7"
      - "&7Rright click to reset tag"
      PlayerHead: true
      # Type: ""
      # Head: ""
    Next:
      Name: "&cNext"
      Head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmZmNTVmMWIzMmMzNDM1YWMxYWIzZTVlNTM1YzUwYjUyNzI4NWRhNzE2ZTU0ZmU3MDFjOWI1OTM1MmFmYzFjIn19fQ=="
      Lore: []
    Previous:
      Name: "&cPrevious"
      Head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjc2OGVkYzI4ODUzYzQyNDRkYmM2ZWViNjNiZDQ5ZWQ1NjhjYTIyYTg1MmEwYTU3OGIyZjJmOWZhYmU3MCJ9fX0="
      Lore: []