gui:
  title: "!#8602e1&lAmazing!#c148f3!#c148f3&lTags!#f74c34"
  categoryTitle: "!#c148f3&lTags!#f74c34 &7&l- &3%category%"
  
  items:
    preview:
      type: "PLAYER_HEAD"
      displayName: "&5&lSelected tag:"
      lore:
      - "&7Selected: %tagname%"
      - "&7Tag: %tag%"
      - "&7"
      - "&7Rright click to reset tag"
      head:
        type: "PLAYER"
        owner: "%player%"
    default:
      type: "NAME_TAG"
      displayName: "&5&l» &7%tag_name%"
      lore:
      - "&7Info: &f%info%"
      - "&7Tag: &f%tag%"
      - ""
      - "%tag% &7%player%"
    next:
      displayName: "&cNext"
      type: "PLAYER_HEAD"
      head:
        type: "VALUES"
        owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmZmNTVmMWIzMmMzNDM1YWMxYWIzZTVlNTM1YzUwYjUyNzI4NWRhNzE2ZTU0ZmU3MDFjOWI1OTM1MmFmYzFjIn19fQ=="
      lore: []
    previous:
      displayName: "&cPrevious"
      type: "PLAYER_HEAD"
      head:
        type: "VALUES"
        owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjc2OGVkYzI4ODUzYzQyNDRkYmM2ZWViNjNiZDQ5ZWQ1NjhjYTIyYTg1MmEwYTU3OGIyZjJmOWZhYmU3MCJ9fX0="
      lore: []