#    EXAMPLE:
#Tags:
#  example:
#    # Tag format that it will use
#    Tag: "&4&lOwner &8&l|&7"
#    # Information that will appear in GUI
#    Info: "Owner tag"
#    Enabled: true

#    # These options are not needed. Just if you want something special for one specific tag...
#    Permission: "specialperm.tag.owner"
#    # Special Name, used instead of path name. 
#    # Example: official name is superTag05, but you do not want player to see this, so you can use this.
#    Name: "SuperExample"

#    # Special actions when tag is selected
#    Select:
#      Commands: []
#      Messages: []
#    
#    # You can find all item options here: https://github.com/TheDevTec/TheAPI/wiki/ItemMaker
#    item:
#      # displayName will be on material in GUI
#      displayName: "&7&l» %tag_name%"
#      lore: []
#      type: "DIAMOND"
#      # If you want to have HEAD as item, you need to set type to "PLAYER_HEAD"¨
#      # and use these settings:
#      head: 
#        type: ""
#        owner: ""

Tags:
  Owner:
    Tag: "&4&lOwner &8&l|&7"
    Info: "Owner tag"
    Enabled: true







##### UPRAVIT ITEM ####
#categories:
#  test:
#    content:
#    - "common"
#    - "quest_2"
#    name: ""
#    #Icom: MATERIAL
#    icon: ""
#    head: ""
#    description:
#    permission: []
#    slot: 5
#    Special options: ALL, PERM,
#    ALL - will show all tags (not needed to add tags in content)
#    PERM - just tags you have perms on
#    special: