#    EXAMPLE:
#Tags:
#  example:
#    # Tag format that it will use
#    Tag: "&4&lOwner &8&l|&7"
#    # Information that will appear in GUI
#    Info: "Owner tag"
#    Enabled: true
#    # This options are not needed. Just if you want something special for one specific tag...
#    Permission: "specialperm.tag.owner"
#    Name will be on material in GUI or will replace placeholder %tagname%
#    Name: ""
#    Lore: []
#    Type: "DIAMOND"
#    Head: ""
#    Select:
#      Commands: []
#      Messages: []

Tags:
  Owner:
    Tag: "&4&lOwner &8&l|&7"
    Info: "Owner tag"
    Enabled: true

#categories:
#  test:
#    content:
#    - "common"
#    - "quest_2"
#    name: ""
#    #Icom: MATERIAL
#    icon: ""
#    head: ""
#    description:
#    permission: []
#    slot: 5
#    Special options: ALL, PERM,
#    ALL - will show all tags (not needed to add tags in content)
#    PERM - just tags you have perms on
#    special: